spring:
  application:
    name: matchday
  http:
    serviceclient:
      the-sports-db:
        base-url: ${THESPORTSDB_BASE_URL:https://www.thesportsdb.com/api/v1/json}
        connect-timeout: 3s
        read-timeout: 10s
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
matchday:
  providers:
    the-sports-db:
      api-key: ${THESPORTSDB_API_KEY:123}
      league-id: ${THESPORTSDB_LEAGUE_ID:4347}
      minimum-request-interval: 2100ms
      max-retries: 2
      fallback-retry-delay: 60s
      maximum-retry-delay: 120s
